### ISSUE TITLE
Failing to add due to errors with datetime field

### ISSUE THREAD

**Issue by conficient** [Lupusa87/BlazorTodosBeta#1]
Not sure if you use the `<InputDate>` component but the *Add Todo* dialog fails (console details below)

The datetime input isn't rendering correctly. The viewed date looks like this:

![image](https://user-images.githubusercontent.com/454494/78775924-f1f67800-798e-11ea-95b9-936493a3807f.png)

but this is the error:
```
Unhandled exception rendering component: The added or subtracted value results in an un-representable DateTime.
```
[edited the console paste]

**Comment by Lupusa87** [comment]
Hello Howard,

 Thank you for letting me know.

 I am checking and it is working from my browser(chrome desktop) now.

 I am making some intensive changes lately and will do general functional
test later.

 I noticed that sometimes browser is not updating app to new version and
still uses old one, so it produces some errors., Please empty cache and
reload to be sure you are seeing latest version.

 Best Regards,
 Vakhtangi Abashidze



 .




ოთხ, 8 აპრ. 2020, 06:50-ში Howard Richards-მა <notifications@github.com>
დაწერა:

**Comment by Lupusa87** [comment]
Please check again and if issue remains I will do more detailed investigation.
